---
- name: Deploy ECS Task and Service with EC2
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "us-east-1"
    ecs_cluster_name: "test-cluster"
    ecs_task_definition_name: "ansible-task-definition"
    ecs_service_name: "ansible-ecs-service"
    ecs_container_name: "ansible_nginx"
    ecs_container_image: "{{ ecs_container_image }}"
    task_definition: null
  tasks:
    - name: Install boto3 library
      pip:
        name: boto3
        executable: /usr/bin/python3
        state: present

    - name: Create ECS Cluster
      command: "aws ecs create-cluster --cluster-name {{ ecs_cluster_name }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      ignore_errors: yes  # Ignore errors if the cluster already exists

    - name: Create ECS Task Definition
      ecs_taskdefinition:
        region: "{{ aws_region }}"
        family: "{{ ecs_task_definition_name }}"
        network_mode: awsvpc
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        execution_role_arn: "arn:aws:iam::736116236436:role/ecsTaskExecutionRole"
        containers:
          - name: "{{ ecs_container_name }}"
            image: "{{ ecs_container_image }}"
            portMappings:
              - containerPort: 80
            memoryReservation: 100
            memory: 250
            cpu: 100
        state: present
      register: task_definition

    - name: Register ECS Task Definition
      debug:
        var: task_definition
